### ISSUE TITLE
Document thread safety

### ISSUE THREAD

**Issue by jhalterman** [failsafe-lib/failsafe#201]
Do a better job of documenting thread safety throughout Failsafe.

**Comment by mvonrenteln** [comment]
It's also related to #47 .

I put here some comments of @jhalterman on Reusing RetryPolicy for reference and to extend the documentation later on:

[JHalterman in Issue 47](https://github.com/jhalterman/failsafe/issues/47#issuecomment-238420393):
"RetryPolicy is certainly reusable and shareable. Failsafe will never modify a RetryPolicy, only read them. That said, since RetryPolicy is currently not thread-safe, unexpected behavior could result if reading/writing to it concurrently."

[JHalterman in Issue 47about multithreaded usage](https://github.com/jhalterman/failsafe/issues/47#issuecomment-272523843):
"Perfectly safe to share retry policies, and encouraged, as long as you're not modifying the retry policy while it's in use (in that case, make a copy()). Failsafe itself never modifies the state of a retry policy."

**Comment by jhalterman** [comment]
This is fixed in master.

**Comment by jhalterman** [comment]
3.0 has been released, which includes this documented.
